apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: playlist-service
  labels:
    application: playlist
spec:
  type: NodePort
  selector:
    app: playlist-app
  ports:
    - protocol: TCP
      port: 4001
