apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: web-deployment
  labels:
    app: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app
          image: 'TODO: add docker images'
          ports:
            - containerPort: 1234
          resources:
            requests:
              memory: '64Mi'
              cpu: '250m'
            limits:
              memory: '600Mi'
              cpu: '500m'
