apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: web-hpa
  namespace: default
  labels:
    application: web-service
spec:
  minReplicas: 3
  maxReplicas: 12
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-deployment
  targetCPUUtilizationPercentage: 80
