apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: web-service
  labels:
    application: web
spec:
  type: NodePort
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 1234
